name: mgkit-dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - blosc=1.17.0
  - bzip2=1.0.8
  - ca-certificates=2019.11.28
  - certifi=2019.11.28
  - cffi=1.13.2
  - chardet=3.0.4
  - click=7.0
  - cryptography=2.8
  - curl=7.65.3
  - cycler=0.10.0
  - decorator=4.4.1
  - entrypoints=0.3
  - filelock=3.0.10
  - flake8=3.7.9
  - freetype=2.10.0
  - future=0.18.2
  - hdf5=1.10.5
  - htseq=0.11.2
  - idna=2.8
  - importlib_metadata=0.23
  - inflect=4.1.0
  - jaraco.itertools=5.0.0
  - kiwisolver=1.1.0
  - krb5=1.16.3
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.65.3
  - libcxx=9.0.1
  - libdeflate=1.3
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgfortran=4.0.0
  - liblapack=3.8.0
  - libllvm8=8.0.1
  - libopenblas=0.3.7
  - libpng=1.6.37
  - libssh2=1.8.2
  - llvm-openmp=9.0.0
  - llvmlite=0.31.0
  - matplotlib=3.1.2
  - matplotlib-base=3.1.2
  - mccabe=0.6.1
  - mock=3.0.5
  - ncurses=6.1
  - networkx=2.4
  - numba=0.48.0
  - numexpr=2.7.0
  - numpy=1.17.3
  - openssl=1.1.1d
  - pandas=0.25.3
  - pandoc=2.9.1.1
  - patsy=0.5.1
  - pip=19.3.1
  - pycodestyle=2.5.0
  - pycparser=2.19
  - pyflakes=2.1.1
  - pymongo=3.9.0
  - pyopenssl=19.1.0
  - pyparsing=2.4.5
  - pysam=0.15.3
  - pysocks=1.7.1
  - pytables=3.6.1
  - python=3.7.3
  - python-dateutil=2.8.1
  - pytz=2019.3
  - readline=8.0
  - requests=2.22.0
  - scipy=1.3.2
  - semidbm=0.5.1
  - setuptools=42.0.2
  - six=1.13.0
  - sqlite=3.30.1
  - statsmodels=0.10.2
  - tk=8.6.10
  - toml=0.10.0
  - tornado=6.0.3
  - tox=3.14.3
  - tqdm=4.40.0
  - urllib3=1.25.7
  - virtualenv=16.7.5
  - wheel=0.33.6
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
    - alabaster==0.7.12
    - appnope==0.1.0
    - attrs==19.3.0
    - babel==2.7.0
    - backcall==0.1.0
    - bleach==3.1.0
    - blockdiag==1.5.4
    - bumpversion==0.5.3
    - defusedxml==0.6.0
    - docutils==0.15.2
    - funcparserlib==0.3.6
    - imagesize==1.1.0
    - importlib-metadata==1.1.0
    - ipykernel==5.1.3
    - ipython==7.10.1
    - ipython-genutils==0.2.0
    - jedi==0.15.1
    - jinja2==2.10.3
    - jsonschema==3.2.0
    - jupyter-client==5.3.4
    - jupyter-console==6.0.0
    - jupyter-core==4.6.1
    - keyring==21.1.0
    - markupsafe==1.1.1
    - mistune==0.8.4
    - more-itertools==8.0.0
    - msgpack-python==0.5.6
    - nbconvert==5.6.1
    - nbformat==4.4.0
    - nbsphinx==0.5.0
    - packaging==19.2
    - pandocfilters==1.4.2
    - parso==0.5.1
    - pathlib==1.0.1
    - pbr==5.4.4
    - pexpect==4.7.0
    - pickleshare==0.7.5
    - pillow==6.2.1
    - pkginfo==1.5.0.1
    - pluggy==0.13.1
    - prompt-toolkit==3.0.2
    - psutil==5.6.7
    - ptyprocess==0.6.0
    - py==1.8.0
    - pygments==2.5.2
    - pyrsistent==0.15.6
    - pytest==5.3.1
    - pytest-console-scripts==0.2.0
    - pytest-datadir==1.3.1
    - pytest-runner==5.2
    - pyzmq==18.1.1
    - readme-renderer==24.0
    - reportlab==3.5.32
    - requests-toolbelt==0.9.1
    - snowballstemmer==2.0.0
    - sphinx==2.2.2
    - sphinx-argparse==0.2.5
    - sphinx-click==2.3.1
    - sphinx-rtd-theme==0.4.3
    - sphinxcontrib-applehelp==1.0.1
    - sphinxcontrib-blockdiag==1.5.5
    - sphinxcontrib-devhelp==1.0.1
    - sphinxcontrib-htmlhelp==1.0.2
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.2
    - sphinxcontrib-serializinghtml==1.1.3
    - testpath==0.4.4
    - traitlets==4.3.3
    - twine==3.1.1
    - vprof==0.37.6
    - wcwidth==0.1.7
    - webcolors==1.10
    - webencodings==0.5.1
    - zipp==0.6.0

